// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hoguqtujkxnbqnkxenag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhvZ3VxdHVqa3huYnFua3hlbmFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI2OTc1NTYsImV4cCI6MjA4ODI3MzU1Nn0.OVe9TgM7vWMndtK3xH2P4IeOH63ZJFRe3Eih0r3Xerg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});